export const GET_POSTS_LIST_PENDING = 'GET_POSTS_LIST_PENDING'
export const GET_POSTS_LIST_SUCCESS = 'GET_POSTS_LIST_SUCCESS'
export const GET_POSTS_LIST_FAIL = 'GET_POSTS_LIST_FAIL'

export const GET_POST_PENDING = 'GET_POST_PENDING'
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'
export const GET_POST_FAIL = 'GET_POST_FAIL'

export const SAVE_POST_PENDING = 'SAVE_POST_PENDING'
export const SAVE_POST_SUCCESS = 'SAVE_POST_SUCCESS'
export const SAVE_POST_FAIL = 'SAVE_POST_FAIL'

export const UPDATE_POST_PENDING = 'UPDATE_POST_PENDING'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL'

export const DELETE_POST_PENDING = 'DELETE_POST_PENDING'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

export const CLEAR_POSTS = 'CLEAR_POSTS'
export const REQUEST_CLEAR_POSTS = 'REQUEST_CLEAR_POSTS'
